### ISSUE TITLE
Are you sure we need Sundials?

### ISSUE THREAD

**Issue by jlperla** [ubcecon/QuantEconLecturePackages.jl#1]
https://github.com/ubcecon/QuantEconLecturePackages.jl/blob/a54c9b57b7e2acfaedeed43bc36d0cea49adf4a3/Project.toml#L33

If not, do a `] rm Sundials` and it should take it out of both.

**Comment by arnavs** [comment]
Don't think we do. I added it to support DiffEqs because of the https://github.com/ubcecon/computing_and_datascience/issues/81.

**Comment by arnavs** [comment]
Done at 995ee4b.
